config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#menu'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/menu', to: 'sessions#menu'

  resources :users, only: [:create, :edit, :update, :destroy]
  resources :contacts
  resources :notes
  resources :events
  resources :todos do
    member do
      post :toggle
    end
  end

  get '*path' => redirect('/')
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true
  validates :body, presence: true

  def start_time
    self.created_at
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user
  before_action :set_user
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = @user.notes.sort_by { |n| n.created_at }
  end

  def show
    @body_with_links = '' + @note.body

    @user.contacts.each do |c|
      @body_with_links.gsub!(/#{c.name}/i, "<a href='/contacts/#{c.id}'>#{c.name}</a>")
    end
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.creator = @user

    if @note.save
      flash[:notice] = 'You created a note'
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      flash[:notice] = 'Your note has been updated'
      redirect_to note_path(@note)
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/views/notes/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='well form-group form_container'>
  <%= form_for @note do |f| %>
    <div class='control-group form_field'>
      <%= f.label :title, class: 'form_label' %>
      <%= f.text_field :title , class: 'form-control'%>
    </div>
    <div class='control-group form_field'>
      <%= f.label :body, class: 'form_label' %>
      <%= f.text_area :body, class: 'form-control', rows: 5 %>
    </div>
    <hr class='form_break'/>
    <div class='control-group'>
      <%= f.submit (@note.new_record? ? 'Submit' : 'Update'), class: 'btn btn-primary form_button submit_button' %>
      <%= link_to 'Cancel', (@note.new_record? ? notes_path : note_path(@note)), class: 'btn btn-primary form_button cancel_button' %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Note' %>
<%= render 'form' %>

<div class='trigger_notes'></div>

app/views/notes/index.html.erb
<%= render 'shared/content_title', title: 'Notes' %>

<div>
  <%= link_to 'Add New Note', new_note_path %>
</div>

<% if @notes.length == 0 %>
  <h4 class='nothing_here'>You have no notes</h4>
<% end %>

<ul class='years_list'>
  <% @notes.reverse.map {|n| n.created_at.year }.uniq.each do |year| %>
  <li>
    <h3><%= year %></h3>
    <ul class='months_list'>
      <% @notes.select {|n| n.created_at.year == year }.map do |y|
                            y.created_at.month
                          end.uniq.each do |month| %>
        <h4><%= Date::MONTHNAMES[month] %></h4>
        <ul class='events_list'>
          <% @notes.select {|n| n.created_at.year == year &&
                                n.created_at.month == month}.each do |note| %>
            <li class='well event_container'>
              <h4><%= link_to note.title, note_path(note) %></h4>
              <small><%= display_datetime(note.created_at) %></small>
            </li>
          <% end %>
        </ul>
      <% end %>
    </ul>
  </li>
  <% end %>
</ul>

<div class='trigger_notes'></div>

app/views/notes/new.html.erb
<%= render 'shared/content_title', title: 'New Note' %>
<%= render 'form' %>

<div class='trigger_notes'></div>

app/views/notes/show.html.erb
<%= render 'shared/content_title', title: @note.title %>

<div class="well span8 show_content">
  <p><%= @body_with_links.html_safe %></p>
  <hr/ class="show_break">
  <h5><small><span class='created_span'>Created:</span> <%= display_datetime(@note.created_at) %></small></h5>
  <% if @note.created_at != @note.updated_at %>
    <h5><small><span class='created_span'>Updated:</span> <%= display_datetime(@note.updated_at) %></small></h5>
  <% end %>
</div>

<div>
  <%= link_to 'Edit Note', edit_note_path, class: 'btn btn-default edit_button' %>
  <%= link_to 'Delete Note', @note,  method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default delete_button' %>
</div>

<div class='trigger_notes'></div>