config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#menu'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/menu', to: 'sessions#menu'

  resources :users, only: [:create, :edit, :update, :destroy]
  resources :contacts
  resources :notes
  resources :events
  resources :todos do
    member do
      post :toggle
    end
  end

  get '*path' => redirect('/')
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true
  validates :start_time, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user
  before_action :set_user
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = @user.events.sort_by { |e| e.start_time }
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator = @user

    if @event.save
      flash[:notice] = "Your event has been created"
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Your event was updated"
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :location, :description, :start_time, :end_time)
  end
end

app/views/events/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='well form-group form_container'>
  <%= form_for @event, html: { class: "event_form" } do |f| %>
    <div class='control-group form_field'>
      <%= f.label :title, class: 'form_label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class='control-group form_field'>
      <%= f.label :location, class: 'form_label' %>
      <%= f.text_field :location, class: 'form-control' %>
    </div>
    <div class='control-group form_field'>
      <%= f.label :description, class: 'form_label' %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class='control-group form_field'>
      <%= f.label :start_time, 'Starts', class: 'form_label' %>
      <%= f.datetime_select :start_time, {}, {class: 'form-control date_select'} %>
    </div>
    <div class='control-group form_field'>
      <%= f.label :end_time, 'Ends', class: 'form_label' %>
      <%= f.datetime_select :end_time, {}, {class: 'form-control date_select'} %>
    </div>
    <hr/>
    <div class='control-group'>
      <%= f.submit (@event.new_record? ? 'Submit' : 'Update'), class: 'btn btn-primary form_button submit_button' %>
      <%= link_to 'Cancel', (@event.new_record? ? events_path : event_path(@event)), class: 'btn btn-primary form_button cancel_button' %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Event' %>

<%= render 'form' %>

<div class='trigger_events'></div>

app/views/events/index.html.erb
<%= render 'shared/content_title', title: 'Events' %>

<div>
  <%= link_to 'Add New Event', new_event_path %>
</div>

<% if @events.length == 0 %>
  <h4 class='nothing_here'>You have no events</h4>
<% end %>

<ul class='years_list'>
  <% @events.reverse.map {|e| e.start_time.year }.uniq.each do |year| %>
  <li>
    <h3><%= year %></h3>
    <ul class='months_list'>
      <% @events.select {|e| e.start_time.year == year }.map do |y|
                            y.start_time.month
                          end.uniq.each do |month| %>
        <h4><%= Date::MONTHNAMES[month] %></h4>
        <ul class='events_list'>
          <% @events.select {|e| e.start_time.year == year &&
                                e.start_time.month == month}.each do |event| %>
            <li class='well event_container'>
              <h4><%= link_to event.title, event_path(event) %></h4>
              <% if start_and_end_date_equal?(event) %>
                <small><%= display_datetime(event.start_time) %></small>
              <% else %>
                <small><%= display_date_range(event) %></small>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </ul>
  </li>
  <% end %>
</ul>

<div class='trigger_events'></div>

app/views/events/new.html.erb
<%= render 'shared/content_title', title: 'New Event' %>

<%= render 'form' %>

<div class='trigger_events'></div>

app/views/events/show.html.erb
<%= render 'shared/content_title', {title: @event.title} %>

<div class="well span8 show_content">
  <h4><strong class="header_strong">Location:</strong> <%= @event.location %></h4>
  <h4><strong class="header_strong">Starts:</strong> <%= display_datetime(@event.start_time) %></h4>
  <% if !start_and_end_date_equal?(@event) %>
    <h4><strong class="header_strong">Ends:</strong> <%= display_datetime(@event.end_time) %></h4>
  <% end %>
  <% if @event.description %>
    <hr/ class="show_break">
    <p><%= @event.description %></p>
  <% end %>
  <hr/ class="show_break">
  <h5><small><span class='created_span'>Created:</span> <%= display_datetime(@event.created_at) %></small></h5>
  <% if @event.created_at != @event.updated_at %>
    <h5><small><span class='created_span'>Updated:</span> <%= display_datetime(@event.updated_at) %></small></h5>
  <% end %>
</div>


<div>
  <%= link_to 'Edit Event', edit_event_path, class: 'btn btn-default edit_button' %>
  <%= link_to 'Delete Event', @event,  method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default delete_button' %>
</div>

<div class='trigger_events'></div>