config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#menu'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/menu', to: 'sessions#menu'

  resources :users, only: [:create, :edit, :update, :destroy]
  resources :contacts
  resources :notes
  resources :events
  resources :todos do
    member do
      post :toggle
    end
  end

  get '*path' => redirect('/')
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true
  validates :start_time, presence: true
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :require_user
  before_action :set_user
  before_action :set_todo, only: [:show, :edit, :update, :toggle, :destroy]

  def index
    @todos = @user.todos.sort_by { |t| t.start_time }
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.creator = @user

    if @todo.save
      flash[:notice] = 'Your todo was created'
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = 'Your todo was updated'
      redirect_to todo_path(@todo)
    else
      render :edit
    end
  end

  def toggle
    @todo.completed = !@todo.completed
    @todo.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :description, :start_time)
  end
end

app/views/todos/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='well form-group form_container'>
  <%= form_for @todo do |f| %>
    <div class='control-group form_field'>
      <%= f.label :title, class: 'form_label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class='control-group form_field'>
      <%= f.label :description, class: 'form_label' %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class='control-group form_field'>
      <%= f.label :start_time, 'Due Date', class: 'form_label' %>
      <%= f.datetime_select :start_time, {}, {class: 'form-control date_select'} %>
    </div>
    <hr/>
    <div class='control-group'>
      <%= f.submit (@todo.new_record? ? 'Submit' : 'Update'), class: 'btn btn-primary form_button submit_button' %>
      <%= link_to 'Cancel', (@todo.new_record? ? todos_path : todo_path(@todo)), class: 'btn btn-primary form_button cancel_button' %>
    </div>
  <% end %>
</div>

app/views/todos/_todo_buttons.html.erb
<%= link_to 'Edit Todo', edit_todo_path, class: 'btn btn-default edit_button todo_button' %>
<% if todo.completed %>
  <%= link_to 'Mark as Incomplete', toggle_todo_path(todo), remote: true, method: :post, class: 'btn btn-default incomplete_button todo_button' %>
<% else %>
  <%= link_to 'Mark as Complete', toggle_todo_path(todo), remote: true, method: :post, class: 'btn btn-default complete_button todo_button' %>
<% end %>
<%= link_to 'Delete Todo', todo,  method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default delete_button todo_button' %>

app/views/todos/_todo_list_item.html.erb
<h4><%= link_to todo.title, todo_path(todo) %></h4>
<small><b>Due: </b><%= display_datetime(todo.start_time) %></small>
<hr/ class="show_break">
<% if todo.completed %>
  <div><%= link_to 'Completed', toggle_todo_path(todo), remote: true, method: :post, class: 'btn btn-default incomplete_button' %></div>
<% else %>
  <div><%= link_to 'Incomplete', toggle_todo_path(todo), remote: true, method: :post, class: 'btn btn-primary complete_button' %></div>
<% end %>

app/views/todos/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Todo' %>

<%= render 'form' %>

<div class='trigger_todos'></div>

app/views/todos/index.html.erb
<%= render 'shared/content_title', title: 'Todos' %>

<div>
  <%= link_to 'Add New Todo', new_todo_path %>
</div>

<% if @todos.length == 0 %>
  <h4 class='nothing_here'>You have no todos</h4>
<% end %>

<ul class='years_list'>
  <% @todos.reverse.map {|t| t.start_time.year }.uniq.each do |year| %>
  <li>
    <h3><%= year %></h3>
    <ul class='months_list'>
      <% @todos.select {|t| t.start_time.year == year }.map do |y|
                            y.start_time.month
                          end.uniq.each do |month| %>
        <h4><%= Date::MONTHNAMES[month] %></h4>
        <ul class='events_list'>
          <% @todos.select {|t| t.start_time.year == year &&
                                t.start_time.month == month}.each do |todo| %>
            <li class='well event_container todo_container' data-id='<%= todo.id %>'>
              <%= render 'todo_list_item', todo: todo %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </ul>
  </li>
  <% end %>
</ul>

<div class='trigger_todos'></div>

app/views/todos/new.html.erb
<%= render 'shared/content_title', title: 'New Todo' %>

<%= render 'form' %>
<div class='trigger_todos'></div>

app/views/todos/show.html.erb
<div class="todo_header_wrapper">
  <%= render 'shared/content_title', {title: @todo.title, todo: @todo} %>
</div>  

<div class="well span8 show_content">
  <h4><strong class="header_strong">Due Date:</strong> <%= display_datetime(@todo.start_time) %></h4>
  <% if @todo.description %>
    <hr/ class="show_break">
    <p><%= @todo.description %></p>
  <% end %>
  <hr/ class="show_break">
  <h5><small>Created: <%= display_datetime(@todo.created_at) %></small></h5>
  <% if @todo.created_at != @todo.updated_at %>
    <h5><small>Updated: <%= display_datetime(@todo.updated_at) %></small></h5>
  <% end %>
</div>

<div class="show_todo_buttons">
  <%= render "todo_buttons", todo: @todo %>
</div>

<div class='trigger_todos'></div>

app/views/todos/toggle.js.erb
var $todo = $("li.todo_container[data-id='<%= @todo.id %>']");
var $todoHeader = $(".todo_header_wrapper");
var $todoButtons = $(".show_todo_buttons");

$todo.html("<%= j render partial: 'todo_list_item', locals: { todo: @todo } %>");
$todoHeader.html("<%= j render partial: 'shared/content_title', locals: { title: @todo.title, todo: @todo } %>");
$todoButtons.html("<%=  j render partial: 'todo_buttons', locals: { todo: @todo } %>");