config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#menu'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/menu', to: 'sessions#menu'

  resources :users, only: [:create, :edit, :update, :destroy]
  resources :contacts
  resources :notes
  resources :events
  resources :todos do
    member do
      post :toggle
    end
  end

  get '*path' => redirect('/')
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "", root_path, {class: "glyphicon glyphicon-leaf", aria_hidden: "true"} %>
      <h2 class='navbar-h2'><%= link_to "PLANNER", root_path, :class => 'brand' %></h2>
    </div>
    <div class='navbar_link_list'>
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class='navbar_contacts'>
            <%= link_to "Contacts (#{current_user.contacts.size})", contacts_path %>
          </li>
          <li class='navbar_notes'>
            <%= link_to "Notes (#{current_user.notes.size})", notes_path %>
          </li>
          <li class='navbar_events'>
            <%= link_to "Events (#{current_user.events.size})", events_path %>
          </li>
          <li class='navbar_todos'>
            <%= link_to "Todos (#{current_user.todos.size})", todos_path %>
          </li>
        <% end %>
      </ul>
    </div>

    <% if logged_in? %>
      <div class='btn-group nav_item'>
        <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %>
          <%= current_user.username %>
          <span class='caret'></span>
        <% end %>
        <ul class='dropdown-menu'>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <i class='icon-pencil'></i>
              Edit Account
            <% end %>
          </li>
          <li>
            <%= link_to logout_path(current_user) do %>
              <i class='icon-circle-arrow-left'></i>
              Logout
            <% end %>
          </li>
        </ul>
      </div>
    <% else # logged out %>
      <div class='nav_item'>
        <%= link_to 'Register', register_path, class: 'btn btn-default btn-small edit_button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="nav-container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
  </header>
  <div id="main" role="main">
    <div class="container main_container">
       <div class="row">
        <div class="span12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div> <!--! end of .container -->
  </div> <!--! end of #main -->
</body>
</html>